### ISSUE TITLE
Make Banner the Same Resolution

### ISSUE THREAD

**Issue by chubkey3** [bull28/Brawl-Stars-Database#1]

**Comment by chubkey3** [comment]
banner are in <code>images/maps/banners</code>

**Comment by bull28** [comment]
Map banner images are now all 294 x 84.

**Comment by chubkey3** [comment]
![](https://preview.redd.it/mz7s0l538iaz.jpg?auto=webp&s=6444942dfa17e96a52089bb4d19036d7bf5e8e79)

**Comment by bull28** [comment]
![IMG_1855](https://user-images.githubusercontent.com/108837986/181229734-5e075ac3-ff13-4c0f-8f86-f11fb1ae177a.PNG)
