### ISSUE TITLE
https://codepen.io/unnegative/pen/dVwYBq

### ISSUE THREAD

**Issue by chubkey3** [bull28/Brawl-Stars-Database#22]

**Comment by bull28** [comment]
### _**@ CHUBKEY 3**_
> [`<!DOCTYPE html><html><body><div style="height:500px;width:500px;background:conic-gradient(#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00);border-radius:50%;display:flex;justify-content:center;align-items:center;"><div style="position:relative;height:480px;width:480px;background-color:#000;border-radius:50%;"></div></div></body></html>`](https://camo.githubusercontent.com/cbd35e26d29ac72d9c177331f317f47af7a6f435237ecedf54c4a221e77c91a1/68747470733a2f2f7777772e6b696e64706e672e636f6d2f706963632f6d2f3136352d313635343135325f7472616e73706172656e742d76696b696e672d706e672d62756c6c2d627261776c2d73746172732d706e672d646f776e6c6f61642e706e67)
