### ISSUE TITLE
⠀⠀⠀⠀⠀⠀⠀⠀Brawl Box

### ISSUE THREAD

**Issue by bull28** [bull28/Brawl-Stars-Database#23]
Make all cards the same size in all Brawl Box type.

Add a setting which controls the animation time to open a box. The fastest setting removes all animations and the cards instantly appear on the screen when the box opens.

Update the collection page after the user opens a box.

Instead of an empty screen, add a message when the user does not have enough tokens to open a box.

Change the token claim interface to include a button to claim instead of automatic claiming of tokens. When calling /claimtokens, include a "claim" field in the request and set it to false in order to view the time left without claiming tokens. The response from this endpoint now includes a "tokensAvailable" field which shows the tokens the user can get by claiming right now. The existing "tokensEarned" field is the number of tokens the user just received right now. If they do not claim them, this field will be 0.

Add the border to the user's avatar based on their collection score. The color can be found in the new "avatarColor" field when calling  /resources.

**Comment by chubkey3** [comment]
update token once claiming
