### ISSUE TITLE
ignore

### ISSUE THREAD

**Issue by chubkey3** [bull28/Brawl-Stars-Database#31]
http://www.gradientcss.com/

**Comment by bull28** [comment]
![skulls_repeat](https://user-images.githubusercontent.com/108837986/211259455-7a5e9364-1861-454a-8e8c-8e46488be96e.png)
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⣈⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⢠⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⡄
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣤⣄⣀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠤⠀⠀⠀⠀⠀⢠⣿⣿⣿⠃⠀⠀⠀⠀⠀⠄⠀⠀⠆
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣦⣤⣤⣀⣀⣀⣀⡀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣁⣀⣀⣠⣤⣤⣴⣶⣶⣾⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀⠀⠀⠀⠈⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⡟⠀⢠⢄⡀⠀⠀⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⠃⠀⡇⠀⠙⠲⢄⡀⢰⣿⡿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠙⠛⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⠀⢸⠀⠀⠀⠀⠀⠉⢹⣿⡇⠀⣀⣈⢉⣛⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋⠉⠉⠉⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠟
⣿⣿⣿⣿⣿⣿⣿⠀⣾⠀⠀⠀⠀⠀⠀⢸⣿⣧⠋⣁⡀⠀⠀⠉⢹⣿⠉⢻⣿⣿⣿⡿⣀⡠⠤⠤⠀⢘⢿⣿⠿⣟⣋⣉⣀⣿⠀⠀⠀⠀⠀⠘⣯⠙⢿⣿⣿⣿⣿⣿⣿⣿⣷⣄⡀
⣿⣿⣿⣿⣿⣿⣿⠀⡟⢀⣀⠤⠖⠂⠀⠈⢿⣿⣎⠁⠴⠃⠀⠀⠸⠟⢈⣾⠟⢀⣼⣿⠏⠀⠀⠀⠀⠘⠻⣤⡂⠟⠲⣷⣿⠇⠒⠒⠲⢤⡀⠀⢻⡄⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣷
⣿⣿⣿⣿⣿⣿⣿⣦⡛⠉⠀⠀⠀⢀⡴⠂⠈⠻⢿⣷⣦⣤⣀⣠⣴⣾⢿⣯⡶⠋⠁⣼⠀⠀⠀⠀⠀⠀⠀⠙⢿⡛⠛⠛⠁⠀⠈⠳⢤⡀⠙⡆⢸⡇⡀⠀⠀⠻⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⠠⠖⠉⠀⠀⠀⠀⠀⠉⠉⠛⠛⠛⠉⣡⠟⠋⠁⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⢘⠳⡄⠀⠀⠙⢦⡀⠀⠀⠀⢸⢨⣇⠃⠀⠀⠀⠈⢿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣇⣀⣀⡀⠀⠀⣸⢧⠄⠀⠀⠀⠀⠀⠀⣸⣱⣿⡄⠀⠀⠀⠙⠀⠀⠀⣸⣿⣿⣆⠀⠀⠀⠀⠀⢹⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⡏⠙⠳⢾⣥⠛⢦⣀⠀⠀⠀⢀⣴⣿⡿⣿⡀⠀⠀⠀⠀⢀⣠⣾⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⢿⢿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡶⠀⠀⠀⠀⠀⠀⠀⠀⣿⡀⠀⢀⣀⣿⣦⣄⣈⠙⣒⣶⣿⡿⠋⠀⣿⡇⠀⠀⠀⠀⠀⢹⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠘⣏⢿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⢻⣧⡞⠉⡀⠀⠙⠻⢿⣭⡿⢿⢯⡀⠀⢠⣿⠇⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠸⡌⢿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣷⣄⠱⣄⠀⠀⠀⠀⠀⠘⡆⢱⣴⣿⠏⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠁⠈
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⣴⡾⠛⣿⠛⠛⠛⠛⢻⠓⠻⠿⢿⣶⣦⣤⣤⣤⣤⣶⣿⡿⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠄
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠈⠳⣤⣹⠀⠀⠀⠀⢸⡀⠀⠀⠀⠀⢹⠉⠛⠛⠿⢭⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠘
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠢⡀⠀⠀⠀⠀⠉⠛⠲⠤⣄⣸⡇⠀⠀⠀⠀⡟⠀⠀⠀⠀⣸⣿⣿⣶⣄⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀
⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠈⠲⣄⡀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠒⠒⠼⠥⠤⣤⣄⣰⣿⣿⣿⠿⠟⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀
⠀⠈⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠙⠳⣤⣀⠀⠉⠓⠤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀
⠀⠀⠀⠈⢷⡈⠙⠻⢿⣿⣿⣿⣿⠃⠀⠀⠀⠉⠛⠶⣤⣄⡀⠈⠙⠒⠤⢄⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠖⣩⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⠀⠀
⠀⠀⠀⠀⠀⠻⣄⠀⠀⠀⠉⠙⠋⠀⢲⡄⠀⠀⠀⠀⠀⠉⠙⠻⠶⢦⣤⣀⡀⠀⠉⠉⠉⠀⠀⠀⠀⠀⠀⠐⠒⠊⠉⢁⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠀
⣆⠀⠀⠀⠀⠀⠹⣶⠀⠀⠀⠀⠀⠀⠸⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠛⠛⠶⠶⠶⠦⢤⣤⣤⣤⠤⠴⠶⠚⠉⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀
⣿⣧⡀⠀⠀⠀⠀⠘⣷⡄⠀⠀⠀⠀⠀⠹⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀
⣿⣿⣷⡄⠀⠀⠀⠀⠈⣿⣦⡀⠀⠀⠀⠀⠈⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠉⠉⠁⠀⠀⠉⠉⠙⠻⠿⣿⣇
